version:  '3.3'

services:
#  adminer:
#    image: adminer
#    restart: on-failure
#    ports:
#      - "127.0.0.1:8080:8080"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - traefik

  phpfpm:
    build:
      context: .    
    ports:
      - 9000 
    depends_on:
      - db
    volumes:
      - ./appsrc:/var/www/html/symfony:cached
      - ./logs:/var/log
      - ./conf/pool.conf:/etc/php/7.3/fpm/pool.d/www.conf
      - ./conf/php-fpm.conf:/etc/php/7.3/fpm/php-fpm.conf
    networks:
      - traefik

  nginx:
    image: nginx
    restart: always
    ports:
      - '127.0.0.1:8111:80'
    depends_on:
      - phpfpm
      - db
    volumes:
      - ./appsrc:/var/www/html/symfony:cached
      - ./logs:/var/log/nginx
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpfpm
    networks:
      - traefik
    labels:
      - traefik.http.routers.phpkursova.rule=Host(`phpkursova.vaskovasilev.eu`)
#  nginx:
#    image: nginx:1.15.3-alpine
#    restart: on-failure
#    volumes:
#      - './apps/my-symfony-app/public/:/usr/src/app'

networks:
  traefik:
    external:
      name: downloads_traefik