<?php

namespace AppBundle\Repository;

/**
 * HostBanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostBanRepository extends \Doctrine\ORM\EntityRepository
{
}
