<?php

namespace AppBundle\Repository;

/**
 * ProductCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
