<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailableProducts(){
        $qb = $this->createQueryBuilder('p');
        $qb->where($qb->expr()->orX(
            $qb->expr()->eq('p.isAvailable', ':availability')
        ))
            ->setParameter(':availability', true);
        $products = $qb->getQuery()->getResult();
        return $products;
    }
}
