<?php

namespace AppBundle\Repository;

/**
 * ProductAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAvailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
