<?php

namespace AppBundle\Repository;
use \AppBundle\Entity\CartItem;
use \AppBundle\Entity\Sale;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param CartItem $cartItem
     * @return Sale
     */
    public function createByCartItem(CartItem $cartItem, $guid)
    {
        $sale = new Sale();
        $sale->setProduct($cartItem->getProduct());
        $sale->setUser($cartItem->getUser());
        $sale->setCreatedOn(new \DateTime());
        $sale->setPurchaseId($guid);
        $sale->setQuantity($cartItem->getQuantity());
        $em = $this->getEntityManager();
        $em->persist($sale);
        $em->flush();
        return $sale;
    }

}
