moderator:
    resource: "@ModeratorBundle/Controller/"
    type:     annotation
    prefix:   /moderate

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin


app:
    resource: '@AppBundle/Controller/'
    type: annotation
