app_category:
    resource: "@AppBundle/Controller/CategoryController.php"
    type:     annotation

app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

moderator:
    resource: "@ModeratorBundle/Controller/"
    type:     annotation
    prefix:   /moderate

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin


app:
    resource: '@AppBundle/Controller/'
    type: annotation
