# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\User:
        algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
    #    in_memory:
    #        memory: ~
      user_provider:
        entity:
          class: AppBundle:User
          #property: username // we're using UserInterfaceLoader

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout:
              path:   /logout
              target: /
            anonymous: ~
            pattern: ^/
            form_login:
              provider: user_provider
              login_path: user_login
              check_path: user_login

    role_hierarchy:
      ROLE_ADMIN:   ROLE_EDITOR
      ROLE_EDITOR:  ROLE_USER

    access_control:
      - path: ^/register
        roles: IS_AUTHENTICATED_ANONYMOUSLY

      - path: ^/login
        roles: IS_AUTHENTICATED_ANONYMOUSLY

      - path: ^/
        roles: ROLE_USER

      - path: ^/admin
        roles: ROLE_ADMIN

      - path: ^/moderate/
        roles: ROLE_EDITOR

        #allow_if: "service('app.visitorvalidator').isHostAllowed(request.getClientIp()) ? true : ( service('session').getFlashBag().add('warning', 'You have been banned.')!=null )"

      #request.getClientIp() not in @=service('access_manager').getBannedIPs() ) ?
      #( @=service('session').getFlashBag().add('warning', 'You have been banned.') != false )
      # : false