# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  repo.products:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Product

  repo.categories:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Category

  repo.promotions:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Promotion

  repo.comments:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\ProductComment

  repo.product_availability:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\ProductAvailability

  repo.cartitem:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\CartItem

  repo.sale:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Sale



  app.slugger:
    class: AppBundle\Utils\Slugger
  app.visitorvalidator:
    class: AppBundle\Utils\VisitorValidator
    arguments: ['@doctrine.orm.entity_manager']
  app.requesthelper:
    class: AppBundle\Utils\RequestHelper
    arguments: ['@request_stack']
  app.productsmanager:
    class: AppBundle\Services\ProductsManager
    arguments: [ "@repo.products", "@repo.promotions", "@repo.categories", "@repo.product_availability", "@repo.comments", "@security.token_storage"]
  app.cartmanager:
    class: AppBundle\Services\CartManager
    arguments: [ "@repo.products", "@repo.promotions", "@repo.categories", "@repo.product_availability", "@repo.cartitem", "@repo.sale", "@security.token_storage"]
  app.salesmanager:
    class: AppBundle\Services\SalesManager
    arguments: [ "@repo.sale"]

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
