<?php

namespace AppBundle\Repository;
use \AppBundle\Entity\CartItem;
use \AppBundle\Entity\Sale;
use AppBundle\Entity\User;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param CartItem $cartItem
     * @return Sale
     */
    public function createByCartItem(CartItem $cartItem, $guid)
    {
        $sale = new Sale();
        $sale->setProduct($cartItem->getProduct());
        $sale->setUser($cartItem->getUser());
        $sale->setCreatedOn(new \DateTime());
        $sale->setPurchaseId($guid);
        $sale->setQuantity($cartItem->getQuantity());
        $em = $this->getEntityManager();
        $em->persist($sale);
        $em->flush();
        return $sale;
    }

    /**
     * @param User $user
     * @return Sale[]
     */
    public function getByUser(User $user)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->eq('s.user', ':user'))
            ->setParameter(':user', $user);
        $item = $qb->getQuery()->getResult();
        return $item;
    }

}
